### ISSUE TITLE
Using w/ llvm/clang's lldb?

### ISSUE THREAD

**Issue by zenspider** [rocky/emacs-dbgr#30]
You know of any support for this? I don't want to write one if I don't have to.

**Comment by josteink** [comment]
I'm assuming this is known, but just in case it isn't...

There was a patch submitted to Emacs mainline for basic LLDB support in GUD, but RMS has been stalling on it.

The patch van be found here: http://lists.gnu.org/archive/html/emacs-devel/2015-02/msg00274.html

**Comment by bvstraalen** [comment]
Is there someway to apply pressure?    I have a team at Lawrence Berkeley National Lab that is an emacs-gdb IDE team and I want to roll out lldb and this would be the easiest way to keep them using emacs.

Brian Van Straalan

**Comment by josteink** [comment]
Technically speaking Stefan Monnier is the maintainer, so he can override RMS.

Anyway it's a public mailing list. Revive the thread?

**Comment by rocky** [comment]
> There was a patch submitted to Emacs mainline for basic LLDB support in GUD, but RMS has been stalling on it.

I'll resist the obvious pun between stalling and Stallman.

That patch isn't of direct use in this project because this is largely a rewrite and there's little to no direct code that is shared between the two.

Of course, both projects are similar in that they parse output with regular expressions (which in my opinion is a weakness of *both* projects). 


> Is there someway to apply pressure?

The objection is of a philosophical or moral quality. In such cases, applying pressure doesn't seem like a winning strategy.

But I also find this idea weird in this way. Both this and gud are free software. That allows anyone to fork the code and change it as you see fit. Just keep the license the same, which is what would happen anyway if the patch *were* incorporated.

I suspect that if you wanted to, you could distribute this via MELPA.

And it is here, that I should mention something that's happened since this issue first was opened. You'll notice in commit logs that since Oct 2014, I've been assigning the copyright to FSF. That's because this project was accepted for inclusion into ELPA. (Of course, it's already in MELPA).

Above for GUD, I suggested forking the code. For this adding code to this framework though things are easier. 

A goal was to restructure code so that others could add their own debuggers outside of this project. Basically, look at the code in `realgud/debugger/gdb`, make a copy of that outside this prjoject and revise that calling it something different. Instead of "require-relative" just plain-ol' Emacs Lisp "require" of the pieces you want in the external package.


> Technically speaking Stefan Monnier is the maintainer, so he can override RMS.

He can, but I wouldn't count on it.

> Edit: my guess is that it's easier to implement this outside GNU due to the whole LLVM tension going on with RMS.

**BINGO!**

I think it best to close this issue here. Given the facts, I think this is now best done outside of this project.

**Comment by zenspider** [comment]
I dunno: http://lists.gnu.org/archive/html/emacs-devel/2015-02/msg00611.html

**Comment by josteink** [comment]
I think it's worth checking with Stefan before leaving it completely dead.

He seems OK with it, given that the regular fsf copyright assignments are done.

I'll check into it.

**Comment by rocky** [comment]
> I think it's worth checking with Stefan before leaving it completely dead

I  don't understand why doing this outside of this project is "dead". 

The situation here has been pretty much the same since the beginning: there hasn't been anybody who has wanted this strong enough in this project try to make a serious effort to work on it. (Lots of jabber though.)  

> I'll check into it.

Thanks.

**Comment by bvstraalen** [comment]
In our community clang is the niche compiler on our Macs, on linux we are gcc, on Cray XC30 we are Intel icc, on IBM BlueGene Q we are an IBM xlC shop, on Cray XK6 we are Portland Group C++ and NVIDIA nvcc.   GNU is not going to track the supercomputers faster than the vendors that are being paid money to keep up with them.  GNU Make and Emacs and gud is our preferred IDE and we expect it will remain portable to every platform we are using.    We love gcc and it is not going away.  I work with StarPU in some of my research and that uses gcc plugins.

   We are a bunch of DOE lab scientist that are comfy with Emacs.   I think supporting lldb within Emacs make Emacs more relevant much more than it makes llvm more dominant.   I have developers eyeing the exits for Eclipse…

   What would this look like using and improving a lldb-gud outside the Emacs main release?  do we set up a git repo ?

Brian



On Jun 4, 2015, at 4:49 AM, R. Bernstein <notifications@github.com> wrote:

> I think it's worth checking with Stefan before leaving it completely dead
> 
> I don't understand why doing this outside of this project is "dead".
> 
> The situation here has been pretty much the same since the beginning: there hasn't been anybody who has wanted this strong enough in this project try to make a serious effort to work on it. (Lots of jabber though.)
> 
> I'll check into it.
> 
> Thanks.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Brian Van Straalen         Lawrence Berkeley Lab
BVStraalen@lbl.gov         Computational Research
(510) 486-4976             Division (crd.lbl.gov)

**Comment by josteink** [comment]
Another case for LLDB is that it supports Elf3-binaries while GDB does not.

**Comment by rocky** [comment]
> What would this look like using and improving a lldb-gud outside the Emacs main release?  do we set up a git repo ?

Yes. I honestly think that's the easiest way to go. And it doesn't preclude folding this back into this repository sometime in the future. (But honestly, the way to go is to move stuff out of here rather than more into here.) 

So  to get you started see https://github.com/rocky/realgud-lldb .  I basically used the instructions in https://github.com/rocky/emacs-dbgr/wiki/How-to-add-a-new-debugger and made some of the changes alluded to regarding turning require-relative to require. 

But I've done nothing to try to customize this for the kind of output that lldb produces. 

See 
https://github.com/rocky/emacs-dbgr/wiki/How-to-add-a-new-debugger#customize-file-initel

**Comment by josteink** [comment]
> > What would this look like using and improving a lldb-gud outside the Emacs main release? do we set up a git repo ?
>
> Yes. I honestly think that's the easiest way to go

Before everyone assumes the worst, I've contacted Stefan Monnier, the lead Emacs maintainer on this issue and this is what he has to say:

> > My understanding of this issue is as follows:
>>
>>  * RMS is against incorporating this patch.
>>  * But you are the lead maintainer of Emacs, and this is your call.
>>  * If everything else is in order, you are willing to accept this patch.
>>  * For any Emacs patches to be accepted, the responsible author(s) must sign the FSF copyright assignments.
>>
>> And as far as I've understood things, the reasons the LLDB-patch has yet not been committed is because of the last point? Or are there other reasons?
>
> I think you got it right, yes.
>
> Tho, I think there's one missing element: it was also removed from the LLVM distribution (for the same copyright reasons, basically).
>
>> I'm just an external party with general interest in LLDB-support in GUD, but if that's all stopping this from getting accepted, I'm willing to try to reach out and assist to get this point adressed. Please let me know if and how I can help.
>
> You'd have to track down the author of that patch and get him to sign the corresponding copyright paperwork.  Or get someone else to
(re)write such a patch.
>
> Stefan

I honestly don't think it sounds that hard, certainly not compared to creating and maintaining your own Emacs patches against mainline.

**Comment by rocky** [comment]
> I honestly don't think it sounds that hard, certainly not compared to creating and maintaining your own Emacs patches against mainline.

Sure, handle this any way you want, especially if you or others are doing the work. But the above comment is misrepresenting things a little. *I* never suggested "maintaining your own Emacs patches against mainline."  so I'm not sure where that idea came up. 

If you want to get the existing patch to support lldb incorporated into gud, great. Just do it! 

But...

The reason *this* project was created was because gud is a pig; gud hasn't had someone guiding the code to get better for decades.  That's probably why Stefan asked for this project to get included in to Elpa. (He asked, me, not the other way around.)

An let me close with a little bit of history. Long long time ago, I in fact had my own patch into gud  to support yet another debugger. But  the Emacs release cycle was so slow compared to how I wanted to improve that portion of the gud code,  It was too hard and slow for me to get changes back into gud. Part of that sluggishness is not just gud and the state it is in, but the fact that it is part of Emacs core without there being an external package available. 

So I subsequently asked them to  *remove* my addition.  That way it wouldn't get in the way of maintaining this outside where things could change and get released much faster.  

So in sum, if all you want is that particular piece of code in there and that's good enough in the foreseeable future, again, by all means do whatever you need to do to finish the work. But for myself, I'm not happy with gud, and I think one can do better. Hence this project.
