### ISSUE TITLE
Set breakpoint from source automatically if only one debug session?

### ISSUE THREAD

**Issue by mkleehammer** [rocky/emacs-dbgr#36]
If I understand correctly, the reason a breakpoint cannot be set in a source buffer without it first being associated with a command buffer is because their might be more than one debugging session.

When there is only one debug session, what about having the ability to set a breakpoint in a source buffer and having it be auto-assigned to the sole command buffer?  If there is more than one, then print an error message or even have the user choose one of the existing sessions.  This could even be extended to multiple sessions based on the source buffer's major mode - if there is only one node debug session then all *.js files would be auto-assigned to it but C files would be assigned to the C/C++ debug session.

I'm sure having multiple debugging sessions is crucial in some situations, but I'd guess that having a single one at a time is extremely common.  The convenience of being able to use emacs as a source debugger without the extra complication of dealing with the associations would be fantastic.

**Comment by rocky** [comment]
> If I understand correctly, the reason a breakpoint cannot be set in a source buffer without it first being associated with a command buffer is because their might be more than one debugging session.

Um... possibly. As I see it, it is a little more involved than this.

The way any debugger command in the source buffer is implemented, is that issues that command via a command buffer; the command buffer is a process buffer that interacts with the process running a debugger. 

So if you don't have a command buffer associated for a source buffer, there's no way to issue *any* debugger command. 

But since talk is cheap compared to coding to get something done, let's imagine how this would work.

(I should also say right at the outside, that when it comes to user interface design, I suck at this big-time.)

Clearly as a user, you have to tell emacs that this particular buffer is a source buffer for which there's command buffer out there. I guess you'd do that by setting "shortkey-mode". Right? Shortkey mode has a side effect of making the source buffer read only. It does this not just because it maps simple keys to debugger functions like breakpoints, but also because if you really are in the middle of debugging the code, you probably shouldn't be making modifications to the code or else debugger positions reported can be off. (But since I'm kind of of a permissive guy, you still can modify the source code; you just have to disable the shortkey mode).  

So this shortkey-mode I guess would then check to see if that buffer has a command-buffer association and if not go look for it.  I suppose that could or should be added.

I *have* just added a command to manually associate the current buffer (assumed to be a source-code buffer) with a command buffer that you are prompted for. That command is called `realgud:cmdbuf-associate`.

When I tried it for breakpoints, the results were not all that satisfying.

In the debuggers I've written, I don't allow you to set a breakpoint on a position that the debugger can't confirm is a legitimate place that could be stopped at. (For example setting a breakpoint on a line that is in the middle of a multi-line comment is a breakpoint that will never get triggered. This is perhaps a deficiency of my debuggers. What gdb and some other debuggers will do is tell you that it doesn't have that position registered, but if you want to set it anyway you can. It might happen that down the line that position will get added say as a result of a dynamic loading somehow. 

So even if you do have a command buffer and associate that with a source buffer manually, that still doesn't mean that you'll be able to set a breakpoint in the buffer. 

Also, I'd like to clarify something about finding the associated command buffer. I live inside emacs and that means that over time I'll have all sorts of debug sessions from the past. When you end a debug session, the buffer doesn't automatically disappear. My thinking here is that there is useful information in that buffer, like what command to use if you want to restart the debugger. Or  what positions were seen and stopped at. And finally, because of *realgud* bugs I haven't tracked down, just one invocation of a debugger causes a couple command buffers to get created. (It is interesting and telling to me how many bugs I'm aware of that no one has reported yet.)

That said, I'm open to suggestions as to how to improve things, and god knows what I have is far from ideal. 

My suggestion would be to fork the code and make the changes you suggest and see if it really helps in the way you invision.

**Comment by rocky** [comment]
Haven't heard back, so I'll assume what's there is ok or there's lack of interest in pursuing this further.

**Comment by amelio-vazquez-reina** [comment]
As discussed, I'm definitely interested in this feature, and based on my experience interacting with other Pythonistas, data scientists and the like, I think the Python community will be as well. In my experience, most people haven't heard about RealGUD, but I am sure this will be come a highly desirable feature!

**Comment by rocky** [comment]
There are a lot of things that are of interest. In an open source project we also need people who are interested in it enough to work on it. 

To give a sense of the difficulty for getting volunteers to do work consider the problem of just getting someone like @amelio-vazquez-reina to document his experiences in running ipdb so that others wouldn't encounter the same problems he had.

**Comment by cpitclaudel** [comment]
@rocky I just skimmed through this, so maybe this will not be it, but here's a suggestion (that I could implement, with pointers from you :)

What about the following trick: in realgud-shortkey-mode, instead of complaining if no buffer is attached, we could simply prompt for which buffer to attach to. Bonus points if there's only one, in which case we silently attach.

Would that work? It sounds relatively easy.

**Comment by rocky** [comment]
I'm cool with that and you vote here by doing.

**Comment by cpitclaudel** [comment]
@amelio-vazquez-reina, would that work for you? To set a breakpoint in another file you'd simply enable realgud-shortkey-mode with `C-x C-a C-q` and press `b`.

**Comment by amelio-vazquez-reina** [comment]
That sound perfect @cpitclaudel

**Comment by cpitclaudel** [comment]
Cool, will work on it then.

**Comment by cpitclaudel** [comment]
Btw @amelio-vazquez-reina, do you feel comfortable installing from a git clone? If so, your testing help would be very much welcome!

**Comment by amelio-vazquez-reina** [comment]
Thanks @cpitclaudel I definitely will! I don't know much elisp, but anything I can do to help!

**Comment by cpitclaudel** [comment]
Alright, all set (and promptly merged, too :).

I had to refactor shortkey-mode-setup a bit to make it more robust to random enabling and disabling, but things seem to work (sample size = 1).

@amelio-vazquez-reina, you can test straight from master, in fact :) The new feature is that after starting the debugger you can press `C-x C-a C-q` in any another buffer (in the same mode) and you'll get a prompt asking you which debugger process you want to attach to. Accepting the default should work, and after that you can use debugger commands in that buffer as well.

Give me just a minute to push a tiny extra change.

**Comment by cpitclaudel** [comment]
@amelio-vazquez-reina All set; should be good to go. Let me know if you need help running from source.

**Comment by amelio-vazquez-reina** [comment]
Thanks @cpitclaudel I uninstalled the MELPA version, cloned master locally and then run 
```
 bash ./install-from-git.sh --prefix=~/.emacs.d/emacs-gdbr
```

This worked until I got:
```
Cannot open load file: No such file or directory, list-utils
configure: error: Can't continue until above error is corrected.
```

[Here](https://gist.github.com/amelio-vazquez-reina/fa8f6f47592cea288b552d7dfed8d4fc) is the full trace of the installation.

Strangely, I seem to have `list-utils` installed already:
```
  list-utils         20160414.702  dependency            List-manipulation utility functions
```

**Comment by amelio-vazquez-reina** [comment]
Also, when  I installed from MELPA all I had to do was:
```
(load-library "realgud")
```
to load `realgud`.

Now that I am installing from source (bulinding against `~/.emacs.d/emacs-gdbr`) I presume I have to tell Emacs first where to find `realgud`. 

Would:
```
(add-to-list 'load-path "~/.emacs.d/emacs-gdbr")
```

do the trick?

**Comment by cpitclaudel** [comment]
Ah, I didn't run install-from-git myself :)
Just installing the dependencies, cloning into a folder, and adding that folder to my load path as you suggested seemed to be enough.

**Comment by amelio-vazquez-reina** [comment]
Wow, it worked great! Thanks. I was able to successfully:

1. Launch the debugger on a driver script 
2. Attach to the debugger a buffer containing a module that contains a function invoked by the driver script with `C-x C-a C-q` (it suggested the command buffer right away)
3. Set up a breakpoint on the module with short-keys (`b`)
4. Run until (`c`) hitting this external breakpoint

👍

**Comment by amelio-vazquez-reina** [comment]
I will put this on the wiki.

**Comment by cpitclaudel** [comment]
Wonderful, thanks for testing! :)

**Comment by amelio-vazquez-reina** [comment]
Done: https://github.com/rocky/emacs-dbgr/wiki/How-to-Use#short-key-mode (I put it under `short-key-mode` since I think that's where it belongs, but feel free to modify as needed!).

**Comment by cpitclaudel** [comment]
Super-duper :) Feel free to close #100, too.
