### ISSUE TITLE
realgud-populate-common-fn-keys-standard is always run

### ISSUE THREAD

**Issue by dfeich** [rocky/emacs-dbgr#45]
I wanted to disable the standard fn keys bindings.
The function `realgud-populate-common-fn-keys-standard` is always run independent of the settings of the `realgud-populate-common-fn-keys-function` variable. It is executed right after the `if`clause in the `realgud-populate-common-keys` function.

I ended up investigating this due to wanting to prevent realgud from defining f5 which I use for other stuff. There I also found a minor typo, since in `realgud-populate-common-fn-keys-standard` the f5 key is bound to `realgud-continue` which should be `realgud:cmd-continue`.

Thanks a lot for providing such a useful package!

**Comment by rocky** [comment]
Honestly, the whole keybinding thing mechanism is a bit of a mystery to me. The "populate-common" functions I think were there to support older versions of emacs that we no longer support. 

Please feel free to dig in and revise all of this in a way that is sensible and consistent with current practice. 

As for the typo, that's been fixed in commit  [e5d0f95]. Thanks for pointing it out.

**Comment by jguenther** [comment]
@rocky: There's still a bug in that function. `realgud:continue` doesn't exist, it looks like the actual command is `realgud:cmd-continue`.

**Comment by rocky** [comment]
Think this is addressed in commit 1790056 . If so please close after checking. 

Thanks for keeping on this.
