### ISSUE TITLE
Invoke GDB indirectly via shell script

### ISSUE THREAD

**Issue by cslux** [rocky/emacs-dbgr#49]
Hey,

I have created a shell script which does a bit houskeeping and invokes at the end GDB. The problem is I can't call this script like `M-x realgud:gdb RET script_name.sh RET` as realgud complains that it can't find the command buffer for buffer *XYZ*.

What works, is calling the script from eshell or shell (emacs), that's all, no other windows are shown, nor is the function `gdb-many-windows` available.

Thanks for your help!
Chris

**Comment by rocky** [comment]
My mind-reading powers are non-existent, so unless you are precise and I can reproduce the problem I haven't a clue as to what's wrong and can't help you. (My experience is that most of the human population works this way too.) 

The simplest script for running gdb: 

```
#!/bin/bash
gdb $@
```
works fine.  Create the _smallest_ shell script that gives you a problem. If it is small like the above you can just copy it as I have done above. 

As for `gdb-many-windows`, that isn't "available" because that is part of the _gdb-mi_ package not this one. Functions that are part of this function will generally start with `realgud`. But before you ask, there is no function called `realgud-many-windows` either. The closest function we have is `realgud-cmdbuf-stay-in-source-toggle`.
