### ISSUE TITLE
if: Can’t find a process for buffer

### ISSUE THREAD

**Issue by CodeFalling** [rocky/emacs-dbgr#52]
```
M-x realgud:nodejs

Current directory: /Users/codefalling/code/cleanjs/
Command: node debug /Users/codefalling/code/cleanjs/main.js localhost:5858
debug> connecting to 127.0.0.1:5858 ..< Debugger listening on port 5858
debug> . ok
debug> break in main.js:1
```

Then I try `M-x nodejs-track-mode` in my `main.js`.I got `if: Can’t find a process for buffer`.

**Comment by rocky** [comment]
In the buffer containing  the `debug>` prompt, run `M-x realgud:cmdbuf-info-describe`.  I think that may give more information about what is going on.


This isn't a problem with realgud so much as it is with nodejs and your understanding of how things work.   

In the long run though I'd suggest installing [trepanjs](https://www.npmjs.com/package/trepanjs) and using that instead via `M-x trepanjs`.  And paste that output. 

A lot of the restrictions in working with nodejs comes from the fact that nodejs doesn't do very well with reporting status, where it is, and is limited in the kinds of commands you can give it. That's why I provided trepanjs.

**Comment by CodeFalling** [comment]
I don't know what happend.But it works well now and I can't  reproduce it now.
