### ISSUE TITLE
how to use realgud with gdb

### ISSUE THREAD

**Issue by Mafeuser** [rocky/emacs-dbgr#53]
Hi.
I've just installed it through melpa and decided to try.

My question: how to set breakpoint at non-associated source file.

What I did so far:

M-x realgud:gdb: gdb myBinary
(gdb)  // this buffer is called command buffer.
(gdb) run
(gdb) C-c C-C   // stop the debugged process
(gdb) up/down /// as expected, source buffers will we displayed. These source buffers will automatically be associated to command buffer.
M-x find-file: some file with source code.
  This file is NOT associated to command buffer, I need to do it locally.
M-x realgud:cmdbuf-associate  #. I don't think it associates current buffer. Why? because `Debugger` menu entry does not allow to set any breakpoints afterwards.

regards

**Comment by rocky** [comment]
There may be a slight bug in realgud::cmdbuf-associate in that it doesn't default to a valid cmdbuf. So if you blindly accepted its default rather than use the name of a real command buffer (which would have a name something like `*gdb  <main-program> shell*`), then you'll probably get the results. I'll look into addressing this at some point. In the meantime, don't use the  default name if that name isn't a command buffer.

Use `M-x realgud:cmdbuf-info-describe` to get full information on how a source buffer is associated. If it doesn't look similar to valid ones, then yes you've got a problem.

**Comment by Mafeuser** [comment]
explicit pointing command buffer name helped.
But when I try to set breakpoint within current source file, I get prompt for some file name. Why needed? I pointed path to current file. As a result red point appears at breakpoint position, but `info bre` from command buffer tells that pointer is set in different file (main.cpp if it matters at all).

regards

**Comment by rocky** [comment]
You get prompted for a name when Emacs can find the file  mentioned in gdb's response to the breakpoint command. For example suppose consider the following. 

     $ cd ~
     $ gdb ~/c/ctest
     GNU gdb ...
      ....
     (gdb) break main
     Breakpoint 1 at 0x40159c: file ctest.c, line 80.

SInce this was done in a shell, Emacs hings the current directory is "~" and but "ctest.c" doesn't reside there. It resides in "~/c/". 

If you had done this as you say from inside the file, I suppose realgud should be smarter about associating the unqualified file name "ctest.c" with the file you started out with. 

More information than this, I can' say because I don't have specific details concerning situation. 

In general when reporting problems or getting help, it's best to try to work up the smallest problem or example that exhibits the bug. Also, I'd prefer one issue per problem. That way we can track issues independently

**Comment by Mafeuser** [comment]
Thanks for Your comments.

**Comment by rocky** [comment]
No problem. But if there is other stuff please try to narrow these and come up with small test cases that show the problem. 

If there's information missing in the wiki for help or in using you have insights you want to share with others feel free to use the wiki to add information.

No doubt not everything here has been addressed, (although in recent commits there is better error handling and error messages). But again, break up into separate issues. Thanks.
