### ISSUE TITLE
tab completion

### ISSUE THREAD

**Issue by seanfarley** [rocky/emacs-dbgr#70]
I was hoping to write ipdb support for realgud but it seems that the comint buffer handling the debugger doesn't handle tab completion. Is this a deep emacs issue or could it be made to work with debuggers that have tab completion? (or perhaps I'm doing something wrong?)

**Comment by rocky** [comment]
First, thanks for even offering to add another debugger. So few people do. 

There are two approaches that have been taken. Probably the most promising here is to do something similar to [backtrace](https://github.com/rocky/emacs-dbgr/blob/master/realgud/common/buffer/backtrace.el#L100-L174).  You basically divert output that would normally go to the command buffer some place that you want to capture it &mdash; it doesn't have to be to a buffer, it can captured in a string &mdash; work with that, and divert process output back. 

The second approach I'll mention just because it seems to be the way GNU emacs architected things. Gdb has a "complete" command, ipdb probably doesn't but I kept this in the trepanning debuggers since I figured the gdb folks and GNU emacs (both initially rms) knew what they were doing, and for sure better than I.  So on the realgud side you issue a "complete" command and again capture the output.

**Comment by seanfarley** [comment]
The first approach seems plausible. I'll try to give it a crack.

As for the second approach, does trepan have a keybinded complete shortcut that I missed? The more working code I can dissect, the faster I can finish this, hehe :-)

**Comment by rocky** [comment]
I thought I had some code in a prior instance somewhere, but I don't see it now. 

As for working code, dude, I was going to copy _you_!

**Comment by seanfarley** [comment]
I think I have everything but `backtrace-mode` working. Tab completion is almost there. I must say, your instructions for copying an existing debugger to create a new one were spot on. I was pleasantly surprised with how easy it was to get working.

**Comment by rocky** [comment]
>Tab completion is almost there. I must say, your instructions for copying an existing debugger to create a new one were spot on.

Yay! I am grateful for that. Of late I've also been adding new debuggers outside of this. Down the line I will probably remove some of the obsolete or little used debuggers like pydb, and pydbgr. https://github.com/rocky/realgud-pry is an example of a debugger maintained as a separate project.

**Comment by seanfarley** [comment]
Created PR #71 for this!

**Comment by butala** [comment]
This would be a killer feature (ipydb integration in emacs with tab completion). Thank you for the great work --- looking forward to giving it a try!

**Comment by seanfarley** [comment]
This actually was fixed with PR #71. It's also now available in melpa, so you can install it from there.
