### ISSUE TITLE
PDB debugger issues incorrect commands

### ISSUE THREAD

**Issue by cpitclaudel** [rocky/emacs-dbgr#82]
(or maybe I'm misunderstanding how these commands should be used)

In python/PDB mode, pressing d on a breakpoint yields:

```
(Pdb) delete 4
*** SyntaxError: invalid syntax (<stdin>, line 1)
```

And using `C-c X` yields:

```
(Pdb) clear 14
No breakpoint numbered 14
```

The first one is because `delete` is not a proper PDB command (the right command is `clear`). The second one fail because `clear` takes a breakpoint number, not a line number.

Happy to provide a patch if you point me to the right place :)

**Comment by rocky** [comment]
> Happy to provide a patch if you point me to the right place :)

And I'd be happy to have you provide a patch as I know this will be fixed and tested much better!

You probably want to add some lines like [what is done in Perl's stock debugger](https://github.com/rocky/emacs-dbgr/blob/master/realgud/debugger/perldb/init.el#L111).  Of course you would need to change the format string since Perl's debugger uses yet another set of whacky nonstandard names for gdb commands.

These changes would go in [`realgud/debugger/pdb/init.el`](https://github.com/rocky/emacs-dbgr/blob/master/realgud/debugger/pdb/init.el) near the bottom.  The list of command are in [`realgud/common/cmds.el`](https://github.com/rocky/emacs-dbgr/blob/master/realgud/common/cmds.el)

The format specifiers `%l`,`%f` and so on are in [`realgud/common/send.el`](https://github.com/rocky/emacs-dbgr/blob/master/realgud/common/send.el#L125-L135).

**Comment by cpitclaudel** [comment]
Cool, thanks for the pointers. Will have a look this week-end I hope :)

**Comment by cpitclaudel** [comment]
Ok, I have a task list:

* PDB-specific issues
  - [ ] Typing “clear” in the PDB console doesn't clear RealGUD's breakpoints
  - [ ] ‘c’ asks for args, but ignores them (PDB's “continue” doesn't take args)
  - [ ] STARTED Some python commands are incorrectly mapped [2/3]
    - [ ] “p” or “!” for eval?
      “!” lets you run statements
    - [ ] finish
    - [ ] ‘delete’ is broken
  - [ ] Shell commands are not supported by PDB [1/1]
    - [ ] Typing ‘!’ in RealGUD yields “(Pdb) python *** NameError: name 'python' is not defined”
  - [ ] ‘e’ causes an “invalid syntax” error in PDB
    - [ ] Should ‘e’ just be disabled in PDB?
      Maybe, but not C-c e
    - [ ] eval and eval-region shouldn't work the same in PDB due to significance of newlines
      :eval-region could use ‘;;’ to separate lines? (Is this IPDB specific?)
  - [ ] Pressing ‘1’ yields “realgud-goto-arrow1: Symbol’s function definition is void: realgud:loc-follow”
  - [ ] Clicking on breakpoint says “<left-margin> <down-mouse-1> is undefined <left-margin> <mouse-1> is undefined”

(this is mostly a note-to-self)

**Comment by cpitclaudel** [comment]
(this is a really amazing project, btw)

**Comment by cpitclaudel** [comment]
Ok, I made a pull request for the simple cases. I'd love input on the rest; namely:

* Clearing all PDB breakpoints (by typing `clear` in the PDB console) does not cause RealGUD to clear its internal breakpoint list. Unfortunately, Python doesn't provide feedback on which breakpoints have been deleted after running clear (it just deletes them all).

* `c` (aka `realgud:cmd-continue`) takes an argument, but PDB doesn't know how to use it. Is there a way to tell realGUD to not ask for it? Alternatively, the default behavior could be to just issue `continue`, and only prompt for an argument with a `C-u` prefix arg?

* PDB doesn't know how to eval an arbitrary block; however, one can eval a single expression. Thus `eval` (C-c e) works fine, but `eval-region` (e) doesn't. Is there a way to mark only the latter as undefined?

And of course, I'll be happy to make a patch out of suggestions about these :)

**Comment by rocky** [comment]
"Continue"with an argument isn't really a gdb behavior, so sure it's okay to have it work with a prefix.

As for eval vs eval region if they are separate commands they can of course be enabled or disabled separately. Your pull request undefines some commands other debuggers support. So I guess I just don't understand the question.

As for how to handle clear, One possibility is to issue commands to pdb to get status on things. Things like the equivalent of gdb's "info break". Another possibility assuming the emacs interface is accurate, is to go through the same logic that pdb goes through. 

Because I have something like this front-end interface, I've designed my debuggers to give reasonable status. (It also sometimes helps programmers too).  So maybe I can get you to switch to one of those? The Python debugger is the only one that can actually tell you precisely where you are stopped inside a line by using the bytecode offset and uncompiling source from that context.

**Comment by rocky** [comment]
> (this is a really amazing project, btw)

It needs people like you to work on it. It was written because I hated the cathedral gud code and its features. However I now have my own larger mess to deal with, so I have had my comeuppance. 

That whole command hash thing needs to be localized better. It would be nice to have a way to handle the now myriad ways of remote socket connections, such as for v8, firefox. Even gud has gdb-mi.

**Comment by cpitclaudel** [comment]
Thanks for the replies. I'll prepare a PR for `continue`.

Regarding eval vs eval region, I meant that both of these functions in cmds.el actually end up running the "eval" command offered by the debugger. In any case, with `e` now prompting when the region isn't active, I think it's a solved problem :)

> As for how to handle clear, One possibility is to issue commands to pdb to get status on things. Things like the equivalent of gdb's "info break". Another possibility assuming the emacs interface is accurate, is to go through the same logic that pdb goes through.

Indeed. This sounds like a bit more work; I'll look into it, but no promises :)

> Because I have something like this front-end interface, I've designed my debuggers to give reasonable status. (It also sometimes helps programmers too). So maybe I can get you to switch to one of those? The Python debugger is the only one that can actually tell you precisely where you are stopped inside a line by using the bytecode offset and uncompiling source from that context. 

Not sure what you mean? Do you mean using an alternative to PDB?

**Comment by rocky** [comment]
Yeah, I meant  t[he python trepan debuggers. ](https://pypi.python.org/pypi?name=trepan&:action=display) for example. 

>  This sounds like a bit more work; I'll look into it, but no promises :)

I'm not sweating it since I'm not a big pdb user.

**Comment by cpitclaudel** [comment]
Closing this issue, since I think my PR addresses the core parts of it. I'll open other issues if I find time to improve the `clear` situation. Thanks for your very quick answers (and of course for this really cool debugger interface)!

**Comment by rocky** [comment]
One other thing I just realized. The prompting on continue I also like because I enter keys incorrectly. For example C is to switch to the command buffer and I sometimes make a mistake there.

gdb has a notion of "set confirm" which prompts on commands that have a more drastic action. Possibly there might be a mode for idiots like me that make lots of mistakes in typing so that continue is prompted anyway.

**Comment by cpitclaudel** [comment]
Very good point. I'll make a PR that introduces an option (which will only cover "c" as a first step, but we can extend it)
